env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install:
  - bundle update
language: ruby
rvm:
  - 2.3.3
script:
  - openssl aes-256-cbc -K $encrypted_4c9ffbc517b5_key -iv $encrypted_4c9ffbc517b5_iv -in travis-ci_org.enc -out travis-ci_org -d
  - chmod 600 travis-ci_org
  - bundle exec rake site:deploy --quiet
