env:
  global:
    secure: "PmCZGX0z6Ocqm0mU3/OwnWQn0fSr0H5J0NUVkmMqkefmFaW9Gxsqr0aEoCJRXSZS5gevhjPUcv3k7p1C3ubFhl1ofkMxrHScA9eZa/V6PLD8ONDpnfEjqh0H68fge2gvCVClONR3VepppSu7AEkPEOMVgSao8N07W9NmfW24sCPk2/6SIl6bQ1jc9KoeEaeMWi+MvG2w+klfoLcEmAKAPz5fDZl9HOhu6f+9YnveX4N0gY1ry+bfpZYJPboaLz0drOaY+TztfR9IloZGY11ZDPzwofMS+y9NjMrXt58D9uh71MnNePci5a5opZdUZRNbj45fzbj+WUON99nquo5Llc605PP0lTT7KO1oJ5wVIh8oo+YU5pv8566mlBn2feHuI5gw2+5aQGzZ05S7h9e+eP0cdnlXbOL9r48HvnrNY364n19soY8TAYoAfBrprCb2u+2hD8Z4NsZrAIc32ctgQ/0c2+rp4Ymkble5NrxQvHI8TvUi5/cY1SDuGG4PL7IEKlwYKq7aUelh2koExi7rHPJA3Ps+GhKOskzwe/fjDwsmdTTKb6rk2nYdbH0xceI5iVlEXQtFWXi89ofU/NCuWTiN7g+jZSac4AiaiQjxrj40KM50QPSPaQqgmU9dsSk/CKJIYvFdLASxSl3m52FItXA2u6S4XZJmBTQEJyFfXyo="
install:
  - bundle update
language: ruby
rvm:
  - 2.3.3
script:
  - bundle exec rake site:deploy
