env:
  global:
    secure: "bnpVtq3qyWw6ouK5OHwRH9sbcle0el1yLRb09SC9zmEz37FTYg4uqlS3VWoelbks+nx5HKCExA8nTuZYHQIz87t5T81tIpFDPPMbpyoz2oOMm+lO0dpbKYSmoeL+xX855nMK1Lgwy+UkODSINeUE1HJpkS5l3Puz1b/SnniX1NprtiqhzLDlDIahvYpqLu56Mg5AqtFudCRonjOnmfClJtrLB5YE7yLFJwLxv+2w/ezub4K6eUCIHUNRU8nNJzNWFY5Ucmf770tcF4qfQTPE9c7DeNtgTr7ClyU0P9lmkY+G4a26BMVm8TXcZOIIfzWgGtsXBo5d8JafH380NvZRV+r31YPR1lxayfWhrb829yavnpcS9KzgAf6Na7GoWRmNeE6SBsN7hLNbqDf7lOnejkyld6reI+wxcxrdLJk6MlSQiSnFK8qd1kk1LvF7wp3PPWiPOoKvB40BZ+fhGsJ+RAPiOPYOL4DqMoSvOnLbvaGlGTc63e1E+XjYFlkNI3hxe48ec0IdPxC+ixlO9YWQpDt8b2j+FgJTlv1gmYRiablPtOhppN9xiYfSdrLVDM24S8k2dGNhsMVsDRhDOfuJIfSNWYrc0Ol+jimGyo/PaCJJ/dXiWloDu4iwl6LaLKuADhfko933l9Y+5Vvrl7lGlvPZGdBQ/HcgPrcXNFNtkSw="
install:
  - bundle update
language: ruby
rvm:
  - 2.3.3
script:
  - bundle exec rake site:deploy
