author: jwds
branch: source
copyright:
  comment:
    groovy: |
      /*
       * Copyright (c) 2017 James W.D. Stewart
       * All rights reserved.
       */
    html: |
      <!--
        ~ Copyright (c) 2017 James W.D. Stewart
        ~ All rights reserved.
        -->
    java: |
      /*
       * Copyright (c) 2017 James W.D. Stewart
       * All rights reserved.
       */
    properties: |
      #
      # Copyright (c) 2017 James W.D. Stewart
      # All rights reserved.
      #
    spi: |
      #
      # Copyright (c) 2017 James W.D. Stewart
      # All rights reserved.
      #
    xml: |
      <!--
        ~ Copyright (c) 2017 James W.D. Stewart
        ~ All rights reserved.
        -->
  singleLine:
    text: "Copyright (c) 2017 James W.D. Stewart.  All rights reserved."
    html: "&copy;2017 James W.D. Stewart.&nbsp; All rights reserved."
# description: "Embrace 'The Suck'"
destination: _site
enforce_ssl: "forces.army"
excerpt_separator: "<!-- excerptBreak -->"
exclude:
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - liquid_pluralize
  - liquid_reading_time
include:
  - .gitattributes
  - .gitignore
  - .nojekyll
  - .well-known
  - CNAME
layout: default
logo: "https://assets.forces.army/naked/images/hotlink-ok/keep-calm_301x301.png"
paginate: 5
paginate_path: "/blog/page:num/"
permalink: "/blog/:year/:month/:day/:title/"
published: true
repo: "jwds1978.github.io"
repository: "jwds1978/jwds1978.github.io"
safe: false
show_downloads: false
sitemap: true
social:
  links:
    - https://www.facebook.com/jwds1978
    - https://plus.google.com/115164780760274259502
    - https://www.instagram.com/jwds1978
    - https://twitter.com/jwds1978
    - https://www.youtube.com/channel/UCEvgM-VbahDYiKx_UK1ZHnw
source: .
tag_feed_dir: tag
tag_feed_layout: tag_feed
tag_page_data:
  sitemap: false
tag_page_dir: tag
tag_page_layout: tag_page
theme: jekyll-theme-midnight
timezone: America/Toronto
title: "James W.D. Stewart"
tld: "forces.army"
twitter:
  username: jwds1978
uri:
  aStore: "http://store.forces.army"
  assets: "https://assets.forces.army"
  blog: "https://blog.forces.army"
  googleMaps: "https://www.google.ca/maps/place"
  shortURL: "https://go.forces.army"
url: "https://forces.army"
username: jwds1978
