author: jwds
enforce_ssl: "forces.army"
exclude: README.md
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
include: .well-known
layout: default
outdatedBrowserURI: "https://ob.forces.army"
paginate: 5
paginate_path: "/blog/page:num/"
permalink: "/blog/:year/:month/:day/:title/"
published: true
shortURL: "https://go.forces.army"
show_downloads: false
sitemap: true
theme: jekyll-theme-midnight
timezone: America/Toronto
title: "James W.D. Stewart"
uri:
  assets: "https://assets.forces.army"
  googleMaps: "https://www.google.ca/maps/place"
url: "https://forces.army"
