author: jwds
copyright:
  comment:
    groovy: |
      /*
       * Copyright (c) 2017 James W.D. Stewart
       * All rights reserved.
       */
    html: |
      <!--
        ~ Copyright (c) 2017 James W.D. Stewart
        ~ All rights reserved.
        -->
    java: |
      /*
       * Copyright (c) 2017 James W.D. Stewart
       * All rights reserved.
       */
    properties: |
      #
      # Copyright (c) 2017 James W.D. Stewart
      # All rights reserved.
      #
    spi: |
      #
      # Copyright (c) 2017 James W.D. Stewart
      # All rights reserved.
      #
    xml: |
      <!--
        ~ Copyright (c) 2017 James W.D. Stewart
        ~ All rights reserved.
        -->
  singleLine:
    text: "Copyright (c) 2017 James W.D. Stewart.  All rights reserved."
    html: "&copy;2017 James W.D. Stewart.&nbsp; All rights reserved."
enforce_ssl: "forces.army"
exclude: README.md
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
include: .well-known
layout: default
paginate: 5
paginate_path: "/blog/page:num/"
permalink: "/blog/:year/:month/:day/:title/"
published: true
shortURL: "https://go.forces.army"
show_downloads: false
sitemap: true
theme: jekyll-theme-midnight
timezone: America/Toronto
title: "James W.D. Stewart"
uri:
  assets: "https://assets.forces.army"
  googleMaps: "https://www.google.ca/maps/place"
url: "https://forces.army"
