exclude: README.md
include: .well-known
layout: default
permalink: /:categories/:year/:month/:day/:title.htm
published: true
show_downloads: false
theme: jekyll-theme-midnight
title: James W.D. Stewart
