author: "James Stewart"
exclude: README.md
gems:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
include: .well-known
layout: default
paginate: 5
paginate_path: "/blog/page:num/"
pagination:
  category: posts
  collection: posts
  debug: false
  enabled: true
  limit: 0
  locale: ""
  per_page: 5
  permalink: "/blog/page:num/"
  sort_field: date
  sort_reverse: true
  tag: ""
  title: ":title - Page :num of :max"
  trail:
    after: 2
    before: 2
permalink: /blog/:categories/:year/:month/:day/:title.htm
published: true
safe: false
show_downloads: false
sitemap: true
theme: jekyll-theme-midnight
timezone: America/Toronto
title: James W.D. Stewart
