author: "James Stewart"
baseURL: "https://forces.army"
enforce_ssl: "forces.army"
exclude: README.md
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
include: .well-known
layout: default
paginate: 5
paginate_path: "/blog/page:num/"
permalink: "/blog/:year/:month/:day/:title/"
published: true
shortURL: "http://go.forces.army"
show_downloads: false
sitemap: true
theme: jekyll-theme-midnight
timezone: America/Toronto
title: "James W.D. Stewart"
url: "https://forces.army"
