exclude: README.md
gems: [jekyll-feed, jekyll-sitemap]
include: .well-known
layout: default
permalink: /:categories/:year/:month/:day/:title.htm
published: true
show_downloads: false
sitemap: true
theme: jekyll-theme-midnight
timezone: America/Toronto
title: James W.D. Stewart
