author: jwds
autopages:
  categories:
    layouts:
      - "autopage_category.html"
    permalink: "/category/:cat"
    title: "Posts Within the ':cat' Category"
  tags:
    layouts:
      - "autopage_tags.html"
    permalink: "/tag/:tag"
    title: "Posts Tagged with ':tag'"
  enabled: false
branch: source
copyright:
  comment:
    groovy: |
      /*
       * Copyright (c) 2017 James W.D. Stewart
       * All rights reserved.
       */
    html: |
      <!--
        ~ Copyright (c) 2017 James W.D. Stewart
        ~ All rights reserved.
        -->
    java: |
      /*
       * Copyright (c) 2017 James W.D. Stewart
       * All rights reserved.
       */
    properties: |
      #
      # Copyright (c) 2017 James W.D. Stewart
      # All rights reserved.
      #
    spi: |
      #
      # Copyright (c) 2017 James W.D. Stewart
      # All rights reserved.
      #
    xml: |
      <!--
        ~ Copyright (c) 2017 James W.D. Stewart
        ~ All rights reserved.
        -->
  singleLine:
    text: "Copyright (c) 2017 James W.D. Stewart.  All rights reserved."
    html: "&copy;2017 James W.D. Stewart.&nbsp; All rights reserved."
description: "Embrace 'The Suck'"
destination: _site
enforce_ssl: "forces.army"
exclude:
  - .gitattributes
  - .gitignore
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
gems:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
include:
  - .nojekyll
  - .well-known
  - CNAME
layout: default
logo: "https://assets.forces.army/naked/images/dandelion-pied-lashes_479x471.png"
# paginate: 5
# paginate_path: "/blog/page:num/"
pagination:
  category: posts
  collection: posts
  debug: false
  enabled: true
  limit: 0
  per_page: 5
  permalink: "/blog/page:num/"
  sort_field: date
  sort_reverse: true
  title: "Page :num of :max :: :title"
  trail:
    after: 2
    before: 2
permalink: "/blog/:year/:month/:day/:title/"
published: true
repo: "jwds1978.github.io"
repository: "jwds1978/jwds1978.github.io"
shortURL: "https://go.forces.army"
show_downloads: false
sitemap: true
social:
  links:
    - "https://www.facebook.com/jwds1978"
    - "https://www.instagram.com/jwds1978"
    - "https://twitter.com/jwds1978"
source: .
theme: jekyll-theme-midnight
timezone: America/Toronto
title: "James W.D. Stewart"
twitter:
  username: jwds1978
uri:
  assets: "https://assets.forces.army"
  googleMaps: "https://www.google.ca/maps/place"
url: "https://forces.army"
username: jwds1978
