author: jwds
branch: source
copyright:
  comment:
    groovy: |
      /*
       * Copyright (c) 2017 James W.D. Stewart
       * All rights reserved.
       */
    html: |
      <!--
        ~ Copyright (c) 2017 James W.D. Stewart
        ~ All rights reserved.
        -->
    java: |
      /*
       * Copyright (c) 2017 James W.D. Stewart
       * All rights reserved.
       */
    properties: |
      #
      # Copyright (c) 2017 James W.D. Stewart
      # All rights reserved.
      #
    spi: |
      #
      # Copyright (c) 2017 James W.D. Stewart
      # All rights reserved.
      #
    xml: |
      <!--
        ~ Copyright (c) 2017 James W.D. Stewart
        ~ All rights reserved.
        -->
  full:
    html: |
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0" rel="external license" target="_blank"
        title="Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License"><img alt="Creative Commons Licence :: BY-NC-SA" height="31"
        src="https://assets.forces.army/naked/images/Creative-Commons_by-nc-sa_88x31.png"
        style="border: 0px; float: left; margin-bottom: 10px; margin-right: 10px;" width="88" /></a>
      <span property="dct:title" xmlns:dct="https://purl.org/dc/terms">James W.D. Stewart</span> by <a href="https://forces.army" property="cc:attributionName"
        rel="cc:attributionURL me" title="James W.D. Stewart" xmlns:cc="https://creativecommons.org/ns#">James Stewart</a> is licensed under a <a
        href="https://creativecommons.org/licenses/by-nc-sa/4.0" rel="external license" target="_blank" title="Creative Commons Licence :: BY-NC-SA">Creative
      Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.&nbsp; Based on a work at <a
        href="https://github.com/jwds1978/jwds1978.github.io" rel="dct:source me" target="_blank" title="jwds1978/jwds1978.github.io :: Embrace 'The Suck'"
        xmlns:dct="https://purl.org/dc/terms">https://github.com/jwds1978/jwds1978.github.io</a>.
  singleLine:
    text: "Copyright (c) 2017 James W.D. Stewart.  All rights reserved."
    html: "&copy;2017 James W.D. Stewart.&nbsp; All rights reserved."
defaults:
  - scope:
      path: ""
    values:
      comments: false
      facebook: false
      image:
        height: 301
        path: "https://assets.forces.army/naked/images/hotlink-ok/keep-calm_301x301.png"
        width: 301
      robotsCache: true
      robotsIndex: true
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true
      facebook: true
      image:
        height: 73
        path: "https://assets.forces.army/naked/images/hotlink-ok/suck-my-words_482x073.png"
        width: 482
# description: "Embrace 'The Suck'"
destination: _site
enforce_ssl: "forces.army"
excerpt_separator: "<!-- excerptBreak -->"
exclude:
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - liquid_pluralize
  - liquid_reading_time
include:
  - .gitattributes
  - .gitignore
  - .nojekyll
  - .well-known
  - CNAME
lang: en_CA
layout: default
logo: "https://assets.forces.army/naked/images/hotlink-ok/keep-calm_301x301.png"
paginate: 5
paginate_path: "/blog/page:num/"
permalink: "/blog/:year/:month/:day/:title/"
published: true
repo: "jwds1978.github.io"
repository: "jwds1978/jwds1978.github.io"
safe: false
show_downloads: false
sitemap: true
social:
  links:
    - https://www.facebook.com/jwds1978
    - https://plus.google.com/115164780760274259502
    - https://www.instagram.com/jwds1978
    - https://twitter.com/jwds1978
    - https://www.youtube.com/channel/UCEvgM-VbahDYiKx_UK1ZHnw
source: .
sponsored:
  blog: |
    <span style="font-weight: bolder;">DISCLAIMER:</span>&nbsp; I receive(d) compensation in exchange for writing this article.&nbsp; Although this posting is
    sponsored, all of the opinions are my own.
tag_feed_dir: tag
tag_feed_layout: tag_feed
tag_page_data:
  sitemap: false
tag_page_dir: tag
tag_page_layout: tag_page
theme: jekyll-theme-midnight
timezone: America/Toronto
title: "James W.D. Stewart"
tld: "forces.army"
twitter:
  username: jwds1978
uri:
  aStore: "https://store.forces.army"
  assets: "https://assets.forces.army"
  blog: "https://blog.forces.army"
  close: "https://forces.army/closure"
  disqus: "https://disqus.com/home/forums/jwds"
  googleMaps: "https://www.google.com/maps/search/?api=1&query="
  shortURL: "https://go.forces.army"
url: "https://forces.army"
username: jwds1978
